# Generated by Django 4.2.1 on 2025-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='Отправить?'),
        ),
    ]
