# Generated by Django 4.2.1 on 2025-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_poll_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='Отправить?'),
        ),
    ]
