# Generated by Django 4.2.1 on 2025-01-22 17:49

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_telegramuser_comment'),
        ('notifications', '0003_notification_is_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Название(опционально)')),
                ('text', models.TextField(max_length=4000, verbose_name='Текст')),
                ('is_send', models.BooleanField(default=False, verbose_name='Отправить?')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(to='telegram_users.telegramuser', verbose_name='Получатели'),
        ),
        migrations.AddField(
            model_name='poll',
            name='receivers',
            field=models.ManyToManyField(to='telegram_users.telegramuser', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст'),
        ),
    ]
