# Generated by Django 4.2.1 on 2025-02-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_is_published_poll_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
    ]
