# Generated by Django 4.2.1 on 2025-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_telegramuser_comment'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(to='telegram_users.telegramuser', verbose_name='Участники'),
        ),
    ]
