# Generated by Django 4.2.1 on 2025-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=30, verbose_name='ID канала')),
                ('channel_link', models.URLField(verbose_name='Ссылка на канал')),
            ],
            options={
                'verbose_name': 'Настройки канала',
                'verbose_name_plural': 'Настройки канала',
            },
        ),
        migrations.CreateModel(
            name='SuperGroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=30, verbose_name='ID группы')),
            ],
            options={
                'verbose_name': 'Настройки супер-группы',
                'verbose_name_plural': 'Настройки супер-группы',
            },
        ),
    ]
