# Generated by Django 4.2.1 on 2025-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_alter_telegramuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Комментарий'),
        ),
    ]
