# Generated by Django 4.2.1 on 2025-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0005_alter_telegramuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(db_index=True, max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
