# Generated by Django 4.2.1 on 2025-01-22 17:36

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0003_telegramuser_comment'),
        ('notifications', '0004_post_notification_receivers_poll_receivers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(editable=False, verbose_name='Текст')),
                ('status', models.CharField(choices=[('GOT', 'Получен'), ('IN_PROGRESS', 'В работе'), ('ANSWERED', 'Отвечен')], db_index=True, default='GOT', max_length=15, verbose_name='Статус')),
                ('telegram_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='PostTopicOffer',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(editable=False, verbose_name='Текст')),
                ('status', models.CharField(choices=[('GOT', 'Получен'), ('IN_PROGRESS', 'В работе'), ('ANSWERED', 'Отвечен')], db_index=True, default='GOT', max_length=15, verbose_name='Статус')),
                ('telegram_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предложение темы поста',
                'verbose_name_plural': 'Предложения темы поста',
            },
        ),
        migrations.CreateModel(
            name='PostFeedBackRequest',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('GOT', 'Получен'), ('IN_PROGRESS', 'В работе'), ('ANSWERED', 'Отвечен')], db_index=True, default='GOT', max_length=15, verbose_name='Статус')),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='notifications.post', verbose_name='Пост')),
                ('telegram_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка обратной связи по посту',
                'verbose_name_plural': 'Заявки обратной связи по постам',
            },
        ),
        migrations.CreateModel(
            name='FeedBackRequest',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(editable=False, verbose_name='Текст')),
                ('status', models.CharField(choices=[('GOT', 'Получен'), ('IN_PROGRESS', 'В работе'), ('ANSWERED', 'Отвечен')], db_index=True, default='GOT', max_length=15, verbose_name='Статус')),
                ('telegram_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка обратной связи',
                'verbose_name_plural': 'Заявки обратной связи',
            },
        ),
    ]
