# Generated by Django 4.2.1 on 2025-02-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeedbackrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка обратной связи по посту', 'verbose_name_plural': 'Заявки обратной связи по постам'},
        ),
    ]
