# Generated by Django 4.2.1 on 2025-01-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackRequest',
            new_name='FeedBack',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
