# Generated by Django 4.2.1 on 2025-01-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_rename_feedbackrequest_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttopicoffer',
            name='status',
        ),
    ]
